CREATE DATABASE Practica;
USE Practica

CREATE TABLE Clientes(
id_cliente INT NOT NULL IDENTITY(1,1) PRIMARY KEY, -- USE INT DEBIDO A QUE ES UN NUMERO ENTERO, NOT NULL PARA NO INGRESAR VALORES NULOS, IDENTITY PARA QUE SE INCREMENTE SIN INTERACCION DEL USUARIO, PRIMARY KEY PORQUE ES MI LLAVE PRIMARIA
Nombre VARCHAR(100) NOT NULL, -- USE VARCHAR(100) PARA EL NOMBRE PERMITIENDO HASTA 100 CARACTERES COMO LO REQUIERE EL EJERCICIO, NOT NULL PARA NO INGRESAR VALORES NULOS
Perfil_bio TEXT NOT NULL, -- USE TEXT DEBIDO A QUE SERA UN TEXTO LARGO O UNA NOTA, NOT NULL PARA NO INGRESAR VALORES NULOS
Fechar_registro DATE NOT NULL -- SE USO DATE YA QUE SOLO ES UNA FECHA SIN TIEMPO, NOT NULL PARA NO INGRESAR VALORES NULOS
);


CREATE TABLE Productos(
id_Producto INT NOT NULL IDENTITY(1,1) PRIMARY KEY, -- USE INT PORQUE ES UN VALOR ENTERO, NOT NULL PARA NO INGRESAR VALORES NULOS, IDENTITY PARA QUE SE INCREMENTE SIN INTERACCION DEL USUARIO, PRIMARY KEY PORQUE ES MI LLAVE PRIMARIA
Descripcion VARCHAR(255) NOT NULL, -- USE VARCHAR(255) PARA COLOCAR TEXTO HASTA 255 CARACTERES COMO LO REQUIERE EL EJERCICIO
Precio DECIMAL(10,2) NOT NULL, -- USE DECIMAL(10,2) PORQUE ES UN PRECIO Y SON NUMEROS EXACTOS
Esta_activo BIT NOT NULL -- USE BIT PARA DARLE DOS ESTADOS, 1 PARA ACTIVO / DISPONIBLE Y 0 PARA INACTIVO / AGOTADO
); 


